###
GET http://localhost:3000/index

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=123456

###

GET http://localhost:3000/post/6366e9362564452f490d1750

###

GET http://localhost:3000/post/6366e9362564452f490d175

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message": "this is my new message",
    "sender": "123456" 
}

###

PUT http://localhost:3000/post/6370cd56405dfb73999ca5d9
Content-Type: application/json

{
    "message": "this is the first updated message",
    "sender":"999000"
}